### ISSUE TITLE
Typo on review queue page

### ISSUE THREAD

**Issue by bershanskiy** [videosegments/videosegments-website#1]
There is a typo on the review queue page:
```
Share link (if person have extension)
```

![image](https://user-images.githubusercontent.com/45960703/63558081-088bb400-c511-11e9-899f-50297a7628ea.png)

I hope I'm filing this in the correct place.

**Comment by videosegments** [comment]
Sorry for very late response, I wasn't subscribed to to this repository. 
English is not my native language. Should it be "person has"? 
Thank you for your report!

**Comment by bershanskiy** [comment]
Yes, "person has" is more grammatically correct
However, I don't really understand the intent of this message: these are the regular YouTube links, why would anyone be required to install this extension?

**Comment by videosegments** [comment]
Thank you for your report, I've changed `have` to `has`.
I made this message to clarify that without extension these links will work as regular video (no automatic rewinds).

**Comment by bershanskiy** [comment]
Closing this now since typo is fixed.
